/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-ignore
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

import { QueryResponse } from '@app/earthquake/client/earthquake-api-query-response.type';

export interface paths {
  '/version': {
    get: operations['version'];
  };
  '/catalogs': {
    get: operations['catalogs'];
  };
  '/contributors': {
    get: operations['contributors'];
  };
  '/application.wadl': {
    get: operations['application.wadl'];
  };
  '/query': {
    get: operations['query'];
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  version: {
    responses: {
      /** @description Successful Response */
      200: {
        content: never;
      };
    };
  };
  catalogs: {
    responses: {
      /** @description Successful Response */
      200: {
        content: never;
      };
    };
  };
  contributors: {
    responses: {
      /** @description Successful Response */
      200: {
        content: never;
      };
    };
  };
  'application.wadl': {
    responses: {
      /** @description Successful Response */
      200: {
        content: never;
      };
    };
  };
  query: {
    parameters: {
      query?: {
        starttime?: string;
        endtime?: string;
        updatedafter?: string;
        minlatitude?: number;
        maxlatitude?: number;
        minlongitude?: number;
        latitude?: number;
        longitude?: number;
        minradius?: number;
        maxradius?: number;
        mindepth?: number;
        maxdepth?: number;
        minmagnitude?: number;
        maxmagnitude?: number;
        magnitudetype?: string;
        includeallmagnitudes?: boolean;
        includeallorigins?: boolean;
        includearrivals?: boolean;
        eventid?: string;
        limit?: number;
        offset?: number;
        orderby?: 'time' | 'time-asc' | 'magnitude' | 'magnitude-asc';
        contributor?: string;
        catalog?: string;
        format?: 'quakeml' | 'csv' | 'geojson' | 'kml';
        callback?: string;
        kmlcolorby?: 'age' | 'depth';
        kmlanimated?: boolean;
        eventtype?: string;
        reviewstatus?: 'automatic' | 'reviewed';
        minmmi?: number;
        maxmmi?: number;
        mincdi?: number;
        maxcdi?: number;
        minfelt?: number;
        alertlevel?: 'green' | 'yellow' | 'orange' | 'red' | '*';
        mingap?: number;
        maxgap?: number;
        minsig?: number;
        maxsig?: number;
        producttype?:
          | 'moment-tensor'
          | 'focal-mechanism'
          | 'shakemap'
          | 'losspager'
          | 'dyfi';
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        // patched manually with TS interface generated from response
        content: { 'application/json': QueryResponse };
      };
    };
  };
}
